### PR TITLE
Update ota.xml

### PR DESCRIPTION
**Pull request by andrewwrightt**
Hope I got this right :)

### CODE REVIEW

**Comment by westcripp** [comment]
correct file name https://github.com/ResurrectionRemix-OTA-Server/resurrectionremix-ota-server.github.io/commit/e02c07c47e17b5a7e8e50c5eba7135a20b46d18c

**Comment by akhilnarang** [comment]
@westcripp  only number of "-" in filename and date will matter this won't affect

**Comment by westcripp** [comment]
@akhilnarang  anyways must be keep it right

**Comment by akhilnarang** [comment]
:+1:

**Pull request merged**
