### PR TITLE
Asus Zenfone 2 Z00A

### PR DESCRIPTION
**Pull request by knone1**
submit Asus Zenfone 2 Z00A device

### CODE REVIEW

**Comment by akhilnarang** [comment]
@knone1 only official devices

**Comment by varund7726** [comment]
Wait this isnt official?

**Comment by akhilnarang** [comment]
@varund7726 it isn't in the maintainers list

**Comment by varund7726** [comment]
OK somebody else is?

**Comment by knone1** [comment]
yes its unofficial i just want to submit asus zenfone 2 Z00A devices for official list of RR official

**Comment by varund7726** [comment]
@knone1 Who is the official maintainer for zenfone 2?

**Comment by knone1** [comment]
me @varund7726 i don't know if theres other build for ressurection remix for asus zenfone 2
heres the main thread on xda http://forum.xda-developers.com/zenfone2/development/rom-resurrection-remix-lp-t3187581

**Comment by varund7726** [comment]
@knone1 ok done https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/3c25d0e17e49f5808acacda090aca5364e60ec76

**Comment by knone1** [comment]
Thanks @varund7726 more power on Resurrection Remix

**Comment by varund7726** [comment]
I have also Sent You invite to Join ota Team @knone1

**Pull request merged**
