### PR TITLE
add strings

### PR DESCRIPTION
**Pull request by Fast0n**

### CODE REVIEW

**Comment by varund7726** [comment]
????

**Comment by Fast0n** [comment]
I added string of missing devices

**Comment by akhilnarang** [comment]
@Fast0n the devs will add if they want to...
Anyway @DC07  @SiddheshK15  y u no giv ota ;-;

**Comment by Fast0n** [comment]
Sorry guys

**Comment by varund7726** [comment]
No problem :)

**Comment by Fast0n** [comment]
If I find an update, I can update the link?

**Pull request closed without merging**
